In [1]:
import numpy as np
import pandas as pd
import os

# List of all Files

In [2]:
os.chdir('/Users/ljiang/DAT-746 SocGen Mon hide instructions') 
path = os.getcwd()
path

'/Users/ljiang/DAT-746 SocGen Mon hide instructions'

In [3]:
os.getcwd()

'/Users/ljiang/DAT-746 SocGen Mon hide instructions'

In [4]:
path
files = os.listdir(path)
files[0:10]

['DAT-746',
 'concat socgen new.xlsx',
 'SocGen February Submission (Entities) (2.5.18) (v.1).csv',
 '.DS_Store',
 'SocGen May Submission (Entities) (5.9.18).csv',
 'SocGenMon January Additions - Entities (1.27.19).xlsx',
 'SocGen March Submission (Individuals) (3.23.18) (v.1).csv',
 'SocGenMon April Additions - Entities (4.25.19).csv',
 'SocGen February Submission (Individuals) (3.5.18) (v.1 - ADDITIONS).csv',
 'SocGen January Submission (Individuals) (1.11.18) (v.1).csv']

In [5]:
len(files)

46

In [44]:
files_csv = [f for f in files if f[-3:] == 'csv']
files_csv[0:10]

['SocGen February Submission (Entities) (2.5.18) (v.1).csv',
 'SocGen May Submission (Entities) (5.9.18).csv',
 'SocGen March Submission (Individuals) (3.23.18) (v.1).csv',
 'SocGenMon April Additions - Entities (4.25.19).csv',
 'SocGen February Submission (Individuals) (3.5.18) (v.1 - ADDITIONS).csv',
 'SocGen January Submission (Individuals) (1.11.18) (v.1).csv',
 'SocGen July Submission (Individuals) (7.27.18).csv',
 'SocGen November Submission (Entities) (11.23.18).csv',
 'SocGen August Submission (Individuals) (8.28.18).csv',
 'SocGen November Submission (Individuals) (11.26.18).csv']

In [7]:
len(files_csv)

38

# Concat First Two and Loop through to Read and Concat the Right Files

In [8]:
data1=pd.read_csv(files_csv[0],encoding='latin-1')
data2=pd.read_csv(files_csv[1],encoding='latin-1')

In [9]:
data1.columns
data1.shape
data1["source_file"]=files_csv[0]
# data1
# data1["source_file"].unique()

In [10]:
data2.columns
data2.shape
data2["source_file"]=files_csv[1]
data2["source_file"].unique()

array(['SocGen May Submission (Entities) (5.9.18).csv'], dtype=object)

In [11]:
data3=pd.concat([data1,data2], axis=0, ignore_index=True)
# data3.columns
# data3.shape
data3
data3["source_file"].unique()

/Users/ljiang/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


array(['SocGen February Submission (Entities) (2.5.18) (v.1).csv',
       'SocGen May Submission (Entities) (5.9.18).csv'], dtype=object)

In [12]:
## concat QA code
for i in range(2,38):
    df1=pd.read_csv(files_csv[i],encoding='latin-1')
    df1["source_file"]=files_csv[i]
    data3=pd.concat([df1,data3], axis=0, ignore_index=True)
    #data3["source_file"][i]=files_csv[i]

/Users/ljiang/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """


In [ ]:
#data3["source_file"].unique()


In [ ]:
data3[0:20]

In [ ]:
len(data3['source_file'].unique())


# Manual import the corrupt file

In [ ]:
os.chdir('/Users/ljiang/Desktop/Rest_of_Socgen') 
path = os.getcwd()
path

In [ ]:
ad_data1=pd.read_csv("SocGen April Submission (Entities) (4.18.18).csv",encoding='latin-1')
ad_data1['source_file']="SocGen April Submission (Entities) (4.18.18).csv"
ad_data1

In [ ]:
ad_data1=ad_data1.drop(['Unnamed: 22','Unnamed: 23','Unnamed: 24','Unnamed: 25','Unnamed: 26','Unnamed: 27'],axis=1)

In [ ]:
ad_data1.columns

In [ ]:
ad_data2=pd.read_csv("SocGen September Submission (Individuals) (9.25.18).csv",encoding='latin-1')
ad_data2['source_file']="SocGen September Submission (Individuals) (9.25.18).csv"

In [ ]:
ad_data2=ad_data2.drop(['Unnamed: 21','Unnamed: 22','Unnamed: 23','Unnamed: 24','Unnamed: 25','Unnamed: 26','Unnamed: 27','Unnamed: 28','Unnamed: 29','Unnamed: 30','Unnamed: 31','Unnamed: 32','Unnamed: 33','Unnamed: 34','Unnamed: 35','Unnamed: 36','Unnamed: 37'],axis=1)

In [ ]:
ad_data2


In [ ]:
## concat all of them 
data3=pd.concat([data3,ad_data1,ad_data2], axis=0, ignore_index=True)

In [ ]:
data3

In [ ]:
data3.to_excel("concat socgen_new 44.xlsx")


In [ ]:
data3.columns

In [ ]:
data3.shape

# QA

In [28]:
len(data3["source_file"].unique())

40

In [29]:
data3.shape
len(data3[data3["ACTION"]=="DELETE"])+len(data3[data3["ACTION"]=='DELETE (BDR already in DDIQ)'])+len(data3[data3["ACTION"]=='DELETE (Duplicate Name - BDR added to another profile)'])

1230

In [30]:
len(data3[data3['ACTION (10.30.17)']=='DELETE (BDR already in DDIQ)'])+len(data3[data3['ACTION (10.30.17)']=='DELETE (Duplicate Name - BDR added to another profile)'])

3

In [31]:
len(data3[data3["ACTION (11.1.17)"]=='DELETE (Duplicate Name - BDR added to another profile)'])

2

In [32]:
len(data3[data3['ACTION (11.6.17)']=='Delete (Dummy Account)'])

1

In [33]:
len(data3[data3["Action"]=='DELETE'])

646

In [34]:
len(data3[data3["Action2"]=='DELETE'])

42

In [35]:
1230+3+3+646+42

1924

In [36]:
path

'/Users/ljiang/Desktop/Rest_of_Socgen'

In [37]:
data3["ACTION"].unique()

array([nan, 'DELETE', 'Update BDR', 'AMEND NAME',
       'Update BDR / Amend PEP-Status', 'Update PEP-Status',
       'Name Re-Run', 'Name Re-Run / BDR Update', 'Re-Run Name',
       'Update BDr', 'DELETE (BDR already in DDIQ)',
       'DELETE (Duplicate Name - BDR added to another profile)',
       'RE-RUN AS MULTINATIONAL (NEW BDR)', 'Updated BDR', 'NEW ENTITY',
       'NAME UPDATE', 'Update DOB',
       'ARCHIVE FEBRUARY PROFILE AND RE-RUN AS MULTINATIONAL',
       'Update Name (Lookback Period from last refresh to present) - New name is in Column B',
       'Update Name (New name is in Column B)', 'UPDATE BDR'],
      dtype=object)

In [38]:
data3['ACTION (10.30.17)'].unique()

array([nan, 'RE-RUN AS MULTINATIONAL (NEW BDR)', 'Updated BDR',
       'DELETE (BDR already in DDIQ)',
       'DELETE (Duplicate Name - BDR added to another profile)'],
      dtype=object)

In [39]:
data3['ACTION (11.1.17)'].unique()

array([nan, 'DELETE (Duplicate Name - BDR added to another profile)',
       'RE-RUN AS MULTINATIONAL (NEW BDR)', 'Updated BDR'], dtype=object)

In [40]:
data3['ACTION (11.6.17)'].unique()

array([nan, 'Delete (Dummy Account)', 'Updated BDR'], dtype=object)

In [41]:
data3["Action"].unique()

array([nan, 'Multinational Run', 'DELETE', 'Update BDR', 'March Onboard',
       'March Review', 'Update Name', 'Update Name / Update BDR',
       'Run as Multinational / BDR Update'], dtype=object)

In [42]:
data3["Action2"].unique()

array([nan, 'DELETE', 'Update BDR'], dtype=object)

In [45]:
# for i in range(len(data3)):
#     if (data3['ACTION (10.30.17)'][i]=='DELETE (BDR already in DDIQ)' or 'DELETE (Duplicate Name - BDR added to another profile)'):
#         data3["Action"][i]=data3['ACTION (10.30.17)'][i]
        

In [ ]:
for i in range(len(data3)):
    if (data3['ACTION (11.1.17)'][i]=='DELETE (Duplicate Name - BDR added to another profile)'):
        data3["Action"][i]=data3['ACTION (11.1.17)'][i]
        

In [ ]:
for i in range(len(data3)):
    if (data3['ACTION (11.1.17)'][i]=='DELETE (Duplicate Name - BDR added to another profile)'):
        data3["Action"][i]=data3['ACTION (11.1.17)'][i]

In [ ]:
data3[data3["Seed Data"]==76802077237254]


# Merge Original Columns If Needed

In [ ]:
join1=pd.read_excel("join 1 .xlsx")

In [ ]:
join1

In [ ]:
kyc=data3[["KYC"]]
kyc

In [ ]:
new_join=join1.merge(kyc, how='left', left_on="index",right_index=True)

In [ ]:
new_join

In [ ]:
new_join.to_excel("concat_joined_kyc.xlsx")

In [ ]:
name_merge=pd.read_excel("name merge.xlsx")

In [ ]:
new_join=join1.merge(name_merge, how='left', left_on="index",right_on="index")

In [ ]:
new_join

In [ ]:
new_join.to_excel("name_joined_v2.xlsx")